- name: Docker Install
  hosts: all
  become: yes
  roles:
    - docker


- name: Jenkins Install
  hosts: all
  become: yes
  vars_files:
    - group_vars/jenkins.yml
    - group_vars/nginx.yml
  roles:
    - jenkins


- name: Nginx setup
  hosts: all
  become: yes
  vars_files:
    - group_vars/nginx.yml
  roles:
    - nginx