RType: ClientSocket Class Reference
ClientSocket Class Reference
#include <ClientSocket.hpp>
Public Member Functions
ClientSocket ()
~ClientSocket () override
bool init_client (const std::string &ip, int port)
void send (Packet *packet, struct sockaddr_in dest) override
void sendPacket (SplitPacket *packet, struct sockaddr_in dest) override
std::tuple< std::unique_ptr< Packet >, int > receive () override
void run () override
std::tuple< std::unique_ptr< Packet >, int > listen_server ()
void init_fd_set ()
bool isInit () const
void setInit (bool init)
void splitAndSend (Packet *packet, struct sockaddr_in dest) override
void receivePacketAndAddToBuffer ()
std::unique_ptr< Packet > getPacketFromBuffer ()
Public Member Functions inherited from USocket
virtual ~USocket ()=default
Public Attributes
struct sockaddr_in serv_addr
int sockfd
Detailed Description
Definition at line 17 of file ClientSocket.hpp.
Constructor & Destructor Documentation
ClientSocket()
ClientSocket::ClientSocket ()
Definition at line 15 of file ClientSocket.cpp.
References sockfd.
~ClientSocket()
ClientSocket::~ClientSocket () override
Definition at line 54 of file ClientSocket.cpp.
References sockfd.
Member Function Documentation
getPacketFromBuffer()
std::unique_ptr< Packet > ClientSocket::getPacketFromBuffer ()
Definition at line 161 of file ClientSocket.cpp.
init_client()
bool ClientSocket::init_client (const std::string & ip, int port)
Definition at line 71 of file ClientSocket.cpp.
References packet::code, packet::data, packet::data_size, MESSAGE, send(), and serv_addr.
Referenced by main().
init_fd_set()
void ClientSocket::init_fd_set ()
Definition at line 413 of file ClientSocket.cpp.
References sockfd.
Referenced by run().
isInit()
bool ClientSocket::isInit () const
Definition at line 427 of file ClientSocket.cpp.
listen_server()
std::tuple< std::unique_ptr< Packet >, int > ClientSocket::listen_server ()
Definition at line 378 of file ClientSocket.cpp.
References sockfd.
receive()
std::tuple< std::unique_ptr< Packet >, int > ClientSocket::receive () override virtual
Implements USocket.
Definition at line 233 of file ClientSocket.cpp.
References receivePacketAndAddToBuffer().
receivePacketAndAddToBuffer()
void ClientSocket::receivePacketAndAddToBuffer ()
Definition at line 129 of file ClientSocket.cpp.
References sockfd.
Referenced by receive().
run()
void ClientSocket::run () override virtual
Implements USocket.
Definition at line 325 of file ClientSocket.cpp.
References init_fd_set().
Referenced by main().
send()
void ClientSocket::send (Packet * packet, struct sockaddr_in dest) override virtual
Implements USocket.
Definition at line 98 of file ClientSocket.cpp.
References splitAndSend().
Referenced by init_client().
sendPacket()
void ClientSocket::sendPacket (SplitPacket * packet, struct sockaddr_in dest) override virtual
Implements USocket.
Definition at line 110 of file ClientSocket.cpp.
References sockfd.
setInit()
void ClientSocket::setInit (bool init)
Definition at line 437 of file ClientSocket.cpp.
splitAndSend()
void ClientSocket::splitAndSend (Packet * packet, struct sockaddr_in dest) override virtual
Implements USocket.
Definition at line 448 of file ClientSocket.cpp.
References packet::data, and packet::data_size.
Referenced by send().
Member Data Documentation
serv_addr
struct sockaddr_in ClientSocket::serv_addr
Definition at line 39 of file ClientSocket.hpp.
Referenced by init_client().
sockfd
int ClientSocket::sockfd
Definition at line 46 of file ClientSocket.hpp.
Referenced by ClientSocket(), init_fd_set(), listen_server(), receivePacketAndAddToBuffer(), sendPacket(), and ~ClientSocket().
The documentation for this class was generated from the following files:
networking/client/ClientSocket.hpp
networking/client/ClientSocket.cpp