RType: AScene Class Reference
AScene Class Reference
#include <AScene.hpp>
Public Member Functions
AScene (ClientCore *clientCore)
~AScene () override=default
void addComponent (std::shared_ptr< IComponent > component) override
std::vector< std::shared_ptr< IComponent > > getComponents () override
void display (sf::RenderWindow &window) override
void handleEvent (const sf::Event &event, sf::RenderWindow &window) override
void update () override
void pauseScene () override
void resumeScene () override
void stopScene () override
AScene (std::shared_ptr< ServerSocket > serverSocket)
~AScene () override=default
void addEntity (std::shared_ptr< IEntity > entity) override
std::vector< std::shared_ptr< IEntity > > getEntities () override
void addService (std::shared_ptr< IService > service) override
std::vector< std::shared_ptr< IService > > getServices () override
void display () override
void pauseScene () override
void resumeScene () override
void stopScene () override
void restartScene () override
void sendGameState (int clientID) override
void broadcastGameState () override
Public Member Functions inherited from IScene
IScene (ClientCore *clientCore)
virtual ~IScene ()=default
virtual void receiveData ()=0
Public Member Functions inherited from ISceneRType
virtual ~ISceneRType ()=default
virtual void update (std::shared_ptr< Event > event, std::shared_ptr< Packet > packet)=0
virtual void initEntities ()=0
virtual void initServices ()=0
Protected Attributes
std::vector< std::shared_ptr< IComponent > > _components
Protected Attributes inherited from IScene
ClientCore * _clientCore
timeval _pingTime {}
Protected Attributes inherited from ISceneRType
std::vector< std::shared_ptr< IEntity > > _entities
std::vector< std::shared_ptr< IService > > _services
std::shared_ptr< ServerSocket > _serverSocket
Additional Inherited Members
Public Attributes inherited from IScene
bool continueScene = true
Detailed Description
Definition at line 9 of file AScene.hpp.
Constructor & Destructor Documentation
AScene() [1/2]
AScene::AScene (ClientCore * clientCore) inline explicit
Definition at line 11 of file AScene.hpp.
References IScene::IScene().
Referenced by GameScene::GameScene(), MainScene::MainScene(), and MenuScene::MenuScene().
~AScene() [1/2]
AScene::~AScene () override default
AScene() [2/2]
AScene::AScene (std::shared_ptr< ServerSocket > serverSocket) explicit
Definition at line 9 of file AScene.cpp.
~AScene() [2/2]
AScene::~AScene () override default
Member Function Documentation
addComponent()
void AScene::addComponent (std::shared_ptr< IComponent > component) override virtual
Implements IScene.
Definition at line 7 of file AScene.cpp.
addEntity()
void AScene::addEntity (std::shared_ptr< IEntity > entity) override virtual
Implements ISceneRType.
Definition at line 14 of file AScene.cpp.
addService()
void AScene::addService (std::shared_ptr< IService > service) override virtual
Implements ISceneRType.
Definition at line 24 of file AScene.cpp.
broadcastGameState()
void AScene::broadcastGameState () override virtual
Implements ISceneRType.
Definition at line 86 of file AScene.cpp.
Referenced by LobbyScene::update().
display() [1/2]
void AScene::display () override virtual
Implements ISceneRType.
Definition at line 34 of file AScene.cpp.
display() [2/2]
void AScene::display (sf::RenderWindow & window) override virtual
Implements IScene.
Definition at line 16 of file AScene.cpp.
getComponents()
std::vector< std::shared_ptr< IComponent > > AScene::getComponents () override virtual
Implements IScene.
Definition at line 11 of file AScene.cpp.
getEntities()
std::vector< std::shared_ptr< IEntity > > AScene::getEntities () override virtual
Implements ISceneRType.
Definition at line 19 of file AScene.cpp.
getServices()
std::vector< std::shared_ptr< IService > > AScene::getServices () override virtual
Implements ISceneRType.
Definition at line 29 of file AScene.cpp.
handleEvent()
void AScene::handleEvent (const sf::Event & event, sf::RenderWindow & window) override virtual
Implements IScene.
Definition at line 25 of file AScene.cpp.
pauseScene() [1/2]
void AScene::pauseScene () override virtual
Implements IScene.
Definition at line 31 of file AScene.cpp.
pauseScene() [2/2]
void AScene::pauseScene () override virtual
Implements IScene.
restartScene()
void AScene::restartScene () override virtual
Implements ISceneRType.
Definition at line 51 of file AScene.cpp.
References ISceneRType::initEntities(), and ISceneRType::initServices().
resumeScene() [1/2]
void AScene::resumeScene () override virtual
Implements IScene.
Definition at line 43 of file AScene.cpp.
resumeScene() [2/2]
void AScene::resumeScene () override virtual
Implements IScene.
sendGameState()
void AScene::sendGameState (int clientID) override virtual
Implements ISceneRType.
Definition at line 59 of file AScene.cpp.
Referenced by LobbyScene::update().
stopScene() [1/2]
void AScene::stopScene () override virtual
Implements IScene.
Definition at line 55 of file AScene.cpp.
stopScene() [2/2]
void AScene::stopScene () override virtual
Implements IScene.
update()
void AScene::update () override virtual
Implements IScene.
Definition at line 22 of file AScene.cpp.
Member Data Documentation
_components
std::vector<std::shared_ptr<IComponent> > AScene::_components protected
Definition at line 25 of file AScene.hpp.
The documentation for this class was generated from the following files:
src/client/Scenes/AScene.hpp
src/client/Scenes/AScene.cpp