RType: InputComponent Class Reference
InputComponent Class Reference
#include <InputComponent.hpp>
Public Member Functions
InputComponent (ClientCore *core, std::shared_ptr< ClientSocket > socket)
void action () override
void setTexture (const sf::Texture &texture)
void setPosition (sf::Vector2f position)
void setSize (sf::Vector2f size)
void setRect (sf::IntRect rect)
void setIsClicked (bool isClicked)
void display (sf::RenderWindow &window) override
sf::IntRect getRect () const
void handleEvent (const sf::Event &event, sf::RenderWindow &window) override
void handleClick ()
void setText ()
std::string getText ()
Public Member Functions inherited from AComponent
AComponent (ClientCore *clientCore)
~AComponent () override=default
ComponentType getType () const override
void addActionTarget (std::shared_ptr< IComponent > component) override
void addSubComponent (std::shared_ptr< IComponent > component) override
void setAttribute (std::string attribute) override
std::string getAttribute () override
Public Member Functions inherited from IComponent
IComponent (ClientCore *clientCore)
virtual ~IComponent ()=default
Additional Inherited Members
Protected Attributes inherited from IComponent
std::string _attribute
ComponentType _type
std::vector< std::shared_ptr< IComponent > > action_target
std::vector< std::shared_ptr< IComponent > > sub_components
ClientCore * _clientCore
Detailed Description
Definition at line 10 of file InputComponent.hpp.
Constructor & Destructor Documentation
InputComponent()
InputComponent::InputComponent (ClientCore * core, std::shared_ptr< ClientSocket > socket) explicit
Definition at line 9 of file InputComponent.cpp.
References IComponent::_attribute, IComponent::_type, AComponent::AComponent(), and INPUT.
Member Function Documentation
action()
void InputComponent::action () override virtual
Implements IComponent.
Definition at line 33 of file InputComponent.cpp.
display()
void InputComponent::display (sf::RenderWindow & window) override virtual
Implements IComponent.
Definition at line 66 of file InputComponent.cpp.
getRect()
sf::IntRect InputComponent::getRect () const
Definition at line 72 of file InputComponent.cpp.
getText()
std::string InputComponent::getText ()
Definition at line 82 of file InputComponent.cpp.
handleClick()
void InputComponent::handleClick ()
handleEvent()
void InputComponent::handleEvent (const sf::Event & event, sf::RenderWindow & window) override virtual
Implements IComponent.
Definition at line 92 of file InputComponent.cpp.
References setText().
setIsClicked()
void InputComponent::setIsClicked (bool isClicked)
Definition at line 87 of file InputComponent.cpp.
setPosition()
void InputComponent::setPosition (sf::Vector2f position)
Definition at line 44 of file InputComponent.cpp.
setRect()
void InputComponent::setRect (sf::IntRect rect)
Definition at line 60 of file InputComponent.cpp.
setSize()
void InputComponent::setSize (sf::Vector2f size)
Definition at line 54 of file InputComponent.cpp.
setText()
void InputComponent::setText ()
Definition at line 77 of file InputComponent.cpp.
Referenced by handleEvent().
setTexture()
void InputComponent::setTexture (const sf::Texture & texture)
Definition at line 38 of file InputComponent.cpp.
The documentation for this class was generated from the following files:
src/client/Components/Input/InputComponent.hpp
src/client/Components/Input/InputComponent.cpp