RType: ServerSocket Class Reference
ServerSocket Class Reference
#include <ServerSocket.hpp>
Public Member Functions
ServerSocket ()
~ServerSocket () override
void init_server (int port)
void send (Packet *packet, struct sockaddr_in dest) override
void sendPacket (SplitPacket *packet, struct sockaddr_in dest) override
void broadcast (Packet *packet)
std::tuple< std::unique_ptr< Packet >, int > receive () override
void run () override
void addClient (struct sockaddr_in client)
int getClientId (sockaddr_in client)
struct sockaddr_in getClientAddress (int id)
void init_fd_set ()
void splitAndSend (Packet *packet, struct sockaddr_in dest) override
void receivePacketAndAddToBuffer ()
std::vector< std::tuple< int, struct sockaddr_in, std::vector< std::tuple< std::shared_ptr< SplitPacket >, timeval > >, timeval > > & getClients ()
std::tuple< std::unique_ptr< Packet >, int > manageClientsBuffer ()
void setNewClientConnected (int newClientConnected)
int getNewClientId ()
int checkClientsDeconnection ()
void clientDump ()
Public Member Functions inherited from USocket
virtual ~USocket ()=default
Detailed Description
Definition at line 16 of file ServerSocket.hpp.
Constructor & Destructor Documentation
ServerSocket()
ServerSocket::ServerSocket ()
Definition at line 10 of file ServerSocket.cpp.
~ServerSocket()
ServerSocket::~ServerSocket () override
Definition at line 43 of file ServerSocket.cpp.
Member Function Documentation
addClient()
void ServerSocket::addClient (struct sockaddr_in client)
Definition at line 98 of file ServerSocket.cpp.
Referenced by receivePacketAndAddToBuffer().
broadcast()
void ServerSocket::broadcast (Packet * packet)
Definition at line 282 of file ServerSocket.cpp.
checkClientsDeconnection()
int ServerSocket::checkClientsDeconnection ()
Definition at line 444 of file ServerSocket.cpp.
clientDump()
void ServerSocket::clientDump ()
Definition at line 502 of file ServerSocket.cpp.
getClientAddress()
struct sockaddr_in ServerSocket::getClientAddress (int id)
Definition at line 258 of file ServerSocket.cpp.
getClientId()
int ServerSocket::getClientId (sockaddr_in client)
Definition at line 116 of file ServerSocket.cpp.
Referenced by receivePacketAndAddToBuffer().
getClients()
std::vector< std::tuple< int, struct sockaddr_in, std::vector< std::tuple< std::shared_ptr< SplitPacket >, timeval > >, timeval > > & ServerSocket::getClients ()
Definition at line 258 of file ServerSocket.cpp.
getNewClientId()
int ServerSocket::getNewClientId ()
Definition at line 490 of file ServerSocket.cpp.
init_fd_set()
void ServerSocket::init_fd_set ()
Definition at line 225 of file ServerSocket.cpp.
Referenced by run().
init_server()
void ServerSocket::init_server (int port)
Definition at line 56 of file ServerSocket.cpp.
Referenced by main().
manageClientsBuffer()
std::tuple< std::unique_ptr< Packet >, int > ServerSocket::manageClientsBuffer ()
Definition at line 372 of file ServerSocket.cpp.
receive()
std::tuple< std::unique_ptr< Packet >, int > ServerSocket::receive () override virtual
Implements USocket.
Definition at line 133 of file ServerSocket.cpp.
References receivePacketAndAddToBuffer().
receivePacketAndAddToBuffer()
void ServerSocket::receivePacketAndAddToBuffer ()
Definition at line 328 of file ServerSocket.cpp.
References addClient(), getClientId(), and setNewClientConnected().
Referenced by receive().
run()
void ServerSocket::run () override virtual
Implements USocket.
Definition at line 234 of file ServerSocket.cpp.
References init_fd_set().
Referenced by main().
send()
void ServerSocket::send (Packet * packet, struct sockaddr_in dest) override virtual
Implements USocket.
Definition at line 72 of file ServerSocket.cpp.
References splitAndSend().
sendPacket()
void ServerSocket::sendPacket (SplitPacket * packet, struct sockaddr_in dest) override virtual
Implements USocket.
Definition at line 82 of file ServerSocket.cpp.
setNewClientConnected()
void ServerSocket::setNewClientConnected (int newClientConnected)
Definition at line 480 of file ServerSocket.cpp.
Referenced by receivePacketAndAddToBuffer().
splitAndSend()
void ServerSocket::splitAndSend (Packet * packet, struct sockaddr_in dest) override virtual
Implements USocket.
Definition at line 294 of file ServerSocket.cpp.
References packet::data_size.
Referenced by send().
The documentation for this class was generated from the following files:
networking/server/ServerSocket.hpp
networking/server/ServerSocket.cpp