RType: LobbyScene Class Reference
LobbyScene Class Reference
#include <Lobby.hpp>
Public Member Functions
LobbyScene (std::shared_ptr< ServerSocket > serverSocket)
Construct a new LobbyScene:: LobbyScene object.
~LobbyScene () override=default
void initScene ()
initScene, init the scene
void update (std::shared_ptr< Event > event, std::shared_ptr< Packet > packet) override
update, update the scene
void checkBulletDeletion ()
checkBulletDeletion, check the bullet deletion
void checkSpawnerActivation ()
bool allEnemiesLeftScreen ()
void enemyDeletion ()
void initEntities () override
initEntities, init the entities
void initServices () override
initServices, init the services
Public Member Functions inherited from AScene
AScene (ClientCore *clientCore)
~AScene () override=default
void addComponent (std::shared_ptr< IComponent > component) override
addComponent, add a component to the scene
std::vector< std::shared_ptr< IComponent > > getComponents () override
getComponents, get all the components of the scene
void display (sf::RenderWindow &window) override
display, display the scene
void handleEvent (const sf::Event &event, sf::RenderWindow &window) override
handleEvent, handle the event
void update () override
void pauseScene () override
pauseScene, pause the scene
void resumeScene () override
resumeScene, resume the scene
void stopScene () override
stopScene, stop the scene
AScene (std::shared_ptr< ServerSocket > serverSocket)
Construct a new AScene:: AScene object.
~AScene () override=default
void addEntity (std::shared_ptr< IEntity > entity) override
addEntity, add an entity
std::vector< std::shared_ptr< IEntity > > getEntities () override
getEntities, get the entities
void addService (std::shared_ptr< IService > service) override
addService, add a service
std::vector< std::shared_ptr< IService > > getServices () override
getServices, get the services
void display () override
void pauseScene () override
void resumeScene () override
void stopScene () override
void restartScene () override
restartScene, restart the scene
void sendGameState (int clientID) override
sedGameState, send the game state
void broadcastGameState () override
broadcastGameState, broadcast the game state
Public Member Functions inherited from IScene
IScene (ClientCore *clientCore)
virtual ~IScene ()=default
virtual void receiveData ()=0
Public Member Functions inherited from ISceneRType
virtual ~ISceneRType ()=default
Additional Inherited Members
Public Attributes inherited from IScene
bool continueScene = true
Protected Attributes inherited from AScene
std::vector< std::shared_ptr< IComponent > > _components
Protected Attributes inherited from IScene
ClientCore * _clientCore
timeval _pingTime {}
Protected Attributes inherited from ISceneRType
std::vector< std::shared_ptr< IEntity > > _entities
std::vector< std::shared_ptr< IService > > _services
std::shared_ptr< ServerSocket > _serverSocket
Detailed Description
Definition at line 13 of file Lobby.hpp.
Constructor & Destructor Documentation
LobbyScene()
LobbyScene::LobbyScene (std::shared_ptr< ServerSocket > serverSocket) explicit
Construct a new LobbyScene:: LobbyScene object.
Parameters
serverSocket
Definition at line 16 of file Lobby.cpp.
References initScene(), and LobbyScene().
Referenced by LobbyScene().
~LobbyScene()
LobbyScene::~LobbyScene () override default
Member Function Documentation
allEnemiesLeftScreen()
bool LobbyScene::allEnemiesLeftScreen ()
Definition at line 278 of file Lobby.cpp.
Referenced by update().
checkBulletDeletion()
void LobbyScene::checkBulletDeletion ()
checkBulletDeletion, check the bullet deletion
Definition at line 551 of file Lobby.cpp.
Referenced by update().
checkSpawnerActivation()
void LobbyScene::checkSpawnerActivation ()
Definition at line 226 of file Lobby.cpp.
References AScene::broadcastGameState(), ENEMY, generateRandomNumber(), newComponent::id, SPRITESOCKET, and newComponent::type.
Referenced by update().
enemyDeletion()
void LobbyScene::enemyDeletion ()
Definition at line 293 of file Lobby.cpp.
Referenced by update().
initEntities()
void LobbyScene::initEntities () override virtual
initEntities, init the entities
Implements ISceneRType.
Definition at line 37 of file Lobby.cpp.
Referenced by initScene().
initScene()
void LobbyScene::initScene ()
initScene, init the scene
Definition at line 28 of file Lobby.cpp.
References initEntities(), and initServices().
Referenced by LobbyScene().
initServices()
void LobbyScene::initServices () override virtual
initServices, init the services
Implements ISceneRType.
Definition at line 194 of file Lobby.cpp.
Referenced by initScene().
update()
void LobbyScene::update (std::shared_ptr< Event > event, std::shared_ptr< Packet > packet) override virtual
update, update the scene
Parameters
event
packet
Implements ISceneRType.
Definition at line 318 of file Lobby.cpp.
References allEnemiesLeftScreen(), AScene::broadcastGameState(), BULLET, checkBulletDeletion(), checkSpawnerActivation(), enemyDeletion(), newComponent::id, PLAYER, AScene::sendGameState(), SPRITESOCKET, and newComponent::type.
The documentation for this class was generated from the following files:
src/lib/r_type/Scenes/Lobby/Lobby.hpp
src/lib/r_type/Scenes/Lobby/Lobby.cpp