RType: ButtonComponent Class Reference
ButtonComponent Class Reference
#include <ButtonComponent.hpp>
Public Member Functions
ButtonComponent (ClientCore *core, std::shared_ptr< ClientSocket > socket)
void action () override
void setTexture (const sf::Texture &texture)
void setPosition (sf::Vector2f position)
void setSize (sf::Vector2f size)
void setCallback (std::function< void()> callback)
void setRect (sf::IntRect rect)
void display (sf::RenderWindow &window) override
sf::IntRect getRect () const
void handleEvent (const sf::Event &event, sf::RenderWindow &window) override
void handleClickInitServer ()
void handleClickMainScene ()
void handleClickAccessGame ()
void defaultCallback ()
Public Member Functions inherited from AComponent
AComponent (ClientCore *clientCore)
~AComponent () override=default
ComponentType getType () const override
void addActionTarget (std::shared_ptr< IComponent > component) override
void addSubComponent (std::shared_ptr< IComponent > component) override
void setAttribute (std::string attribute) override
std::string getAttribute () override
Public Member Functions inherited from IComponent
IComponent (ClientCore *clientCore)
virtual ~IComponent ()=default
Additional Inherited Members
Protected Attributes inherited from IComponent
std::string _attribute
ComponentType _type
std::vector< std::shared_ptr< IComponent > > action_target
std::vector< std::shared_ptr< IComponent > > sub_components
ClientCore * _clientCore
Detailed Description
Definition at line 15 of file ButtonComponent.hpp.
Constructor & Destructor Documentation
ButtonComponent()
ButtonComponent::ButtonComponent (ClientCore * core, std::shared_ptr< ClientSocket > socket) explicit
Definition at line 10 of file ButtonComponent.cpp.
References IComponent::_attribute, IComponent::_type, AComponent::AComponent(), and BUTTON.
Member Function Documentation
action()
void ButtonComponent::action () override virtual
Implements IComponent.
Definition at line 28 of file ButtonComponent.cpp.
Referenced by handleEvent().
defaultCallback()
void ButtonComponent::defaultCallback ()
Definition at line 178 of file ButtonComponent.cpp.
display()
void ButtonComponent::display (sf::RenderWindow & window) override virtual
Implements IComponent.
Definition at line 62 of file ButtonComponent.cpp.
getRect()
sf::IntRect ButtonComponent::getRect () const
Definition at line 67 of file ButtonComponent.cpp.
handleClickAccessGame()
void ButtonComponent::handleClickAccessGame ()
Definition at line 145 of file ButtonComponent.cpp.
References IComponent::_clientCore, packet::code, packet::data, packet::data_size, MESSAGE, and ClientCore::setCurrentScene().
handleClickInitServer()
void ButtonComponent::handleClickInitServer ()
Definition at line 85 of file ButtonComponent.cpp.
handleClickMainScene()
void ButtonComponent::handleClickMainScene ()
Definition at line 129 of file ButtonComponent.cpp.
References IComponent::_clientCore, and ClientCore::setCurrentScene().
handleEvent()
void ButtonComponent::handleEvent (const sf::Event & event, sf::RenderWindow & window) override virtual
Implements IComponent.
Definition at line 72 of file ButtonComponent.cpp.
References action().
setCallback()
void ButtonComponent::setCallback (std::function< void()> callback)
Definition at line 57 of file ButtonComponent.cpp.
setPosition()
void ButtonComponent::setPosition (sf::Vector2f position)
Definition at line 39 of file ButtonComponent.cpp.
setRect()
void ButtonComponent::setRect (sf::IntRect rect)
Definition at line 51 of file ButtonComponent.cpp.
setSize()
void ButtonComponent::setSize (sf::Vector2f size)
Definition at line 45 of file ButtonComponent.cpp.
setTexture()
void ButtonComponent::setTexture (const sf::Texture & texture)
Definition at line 33 of file ButtonComponent.cpp.
The documentation for this class was generated from the following files:
src/client/Components/Button/ButtonComponent.hpp
src/client/Components/Button/ButtonComponent.cpp