RType: MainScene Class Reference
MainScene Class Reference
#include <MainScene.hpp>
Public Member Functions
MainScene (ClientCore *clientCore, std::shared_ptr< ClientSocket > socket)
MainScene, constructor of MainScene.
~MainScene () override=default
~MainScene, destructor of MainScene
void init_scene ()
init_scene, init the scene
void handleEvent (const sf::Event &event, sf::RenderWindow &window) override
handleEvent, handle the event
void receiveData () override
receiveData, receive the data
Public Member Functions inherited from AScene
AScene (ClientCore *clientCore)
AScene, constructor of AScene.
~AScene () override=default
~AScene, destructor of AScene
void addComponent (std::shared_ptr< IComponent > component) override
addComponent, add a component
std::vector< std::shared_ptr< IComponent > > getComponents () override
getComponents, get all the components
void display (sf::RenderWindow &window) override
display, display the scene
void handleEvent (const sf::Event &event, sf::RenderWindow &window) override
handleEvent, handle the event
void update () override
update, update the scene
void pauseScene () override
pauseScene, pause the scene
void resumeScene () override
resumeScene, resume the scene
void stopScene () override
stopScene, stop the scene
AScene (std::shared_ptr< ServerSocket > serverSocket)
Construct a new AScene:: AScene object.
~AScene () override=default
Destroy the AScene:: AScene object.
void addEntity (std::shared_ptr< IEntity > entity) override
addEntity, add an entity
std::vector< std::shared_ptr< IEntity > > getEntities () override
getEntities, get the entities
void addService (std::shared_ptr< IService > service) override
addService, add a service
std::vector< std::shared_ptr< IService > > getServices () override
getServices, get the services
void display () override
display, display the scene
void pauseScene () override
pauseScene, pause the scene
void resumeScene () override
resumeScene, resume the scene
void stopScene () override
stopScene, stop the scene
void restartScene () override
restartScene, restart the scene
void sendGameState (int clientID) override
sendGameState, send the game state
void broadcastGameState () override
broadcastGameState, broadcast the game state
Public Member Functions inherited from IScene
IScene (ClientCore *clientCore)
IScene, constructor of IScene.
virtual ~IScene ()=default
~IScene, destructor of IScene
Public Member Functions inherited from ISceneRType
virtual ~ISceneRType ()=default
Construct a new IScene:: IScene object.
virtual void update (std::shared_ptr< Event > event, std::shared_ptr< Packet > packet)=0
update, update the scene
virtual void initEntities ()=0
initEntities, init the entities
virtual void initServices ()=0
initServices, init the services
Additional Inherited Members
Public Attributes inherited from IScene
bool continueScene = true
Protected Attributes inherited from AScene
std::vector< std::shared_ptr< IComponent > > _components
Protected Attributes inherited from IScene
ClientCore * _clientCore
timeval _pingTime {}
Protected Attributes inherited from ISceneRType
std::vector< std::shared_ptr< IEntity > > _entities
std::vector< std::shared_ptr< IService > > _services
std::shared_ptr< ServerSocket > _serverSocket
Detailed Description
Definition at line 21 of file MainScene.hpp.
Constructor & Destructor Documentation
MainScene()
MainScene::MainScene (ClientCore * clientCore, std::shared_ptr< ClientSocket > socket) explicit
MainScene, constructor of MainScene.
Construct a new Main Scene:: Main Scene object.
Parameters
clientCore
socket
Definition at line 16 of file MainScene.cpp.
References AScene::AScene(), and init_scene().
~MainScene()
MainScene::~MainScene () override default
~MainScene, destructor of MainScene
Member Function Documentation
handleEvent()
void MainScene::handleEvent (const sf::Event & event, sf::RenderWindow & window) override virtual
handleEvent, handle the event
Parameters
event
window
Implements IScene.
Definition at line 103 of file MainScene.cpp.
init_scene()
void MainScene::init_scene ()
init_scene, init the scene
init_scene, initialize the scene
Definition at line 27 of file MainScene.cpp.
Referenced by MainScene().
receiveData()
void MainScene::receiveData () override virtual
receiveData, receive the data
Implements IScene.
Definition at line 121 of file MainScene.cpp.
References IScene::_pingTime.
The documentation for this class was generated from the following files:
src/client/Scenes/Menu/MainScene.hpp
src/client/Scenes/Menu/MainScene.cpp