RType: Drawable Class Reference
Drawable Class Reference
#include <Drawable.hpp>
Public Member Functions
Drawable ()
char * getAttribute () const override
void setAttribute (std::string attribute) override
Position getPosition () const
void setPosition (std::tuple< float, float > position)
Size getSize () const
void setSize (std::tuple< float, float > size)
Rect getRect () const
void setRect (std::tuple< int, int, int, int > rect)
std::shared_ptr< Packet > getPacket ()
void storeStringInAttributes (std::string str, DrawablePacket *drawablePacket)
void setHasChanged (bool hasChanged)
bool getHasChanged () const
void addDrawableCollision (std::shared_ptr< Drawable > drawableCollision)
std::vector< std::shared_ptr< Drawable > > getDrawablesCollision () const
Public Member Functions inherited from IComponentRType
virtual ~IComponentRType ()=default
Public Attributes
int _textureId
Protected Attributes
Position _position
Size _size
Rect _rect
bool hasChanged = false
std::vector< std::shared_ptr< Drawable > > _drawablesCollision
Protected Attributes inherited from IComponentRType
char * _attribute
Detailed Description
Definition at line 21 of file Drawable.hpp.
Constructor & Destructor Documentation
Drawable()
Drawable::Drawable ()
Definition at line 13 of file Drawable.cpp.
References IComponentRType::_attribute, _textureId, setPosition(), setRect(), and setSize().
Member Function Documentation
addDrawableCollision()
void Drawable::addDrawableCollision (std::shared_ptr< Drawable > drawableCollision)
Definition at line 100 of file Drawable.cpp.
getAttribute()
char * Drawable::getAttribute () const override virtual
Implements IComponentRType.
Definition at line 23 of file Drawable.cpp.
References IComponentRType::_attribute.
getDrawablesCollision()
std::vector< std::shared_ptr< Drawable > > Drawable::getDrawablesCollision () const
Definition at line 104 of file Drawable.cpp.
getHasChanged()
bool Drawable::getHasChanged () const
Definition at line 96 of file Drawable.cpp.
References hasChanged.
getPacket()
std::shared_ptr< Packet > Drawable::getPacket ()
Definition at line 69 of file Drawable.cpp.
References IComponentRType::_attribute, _textureId, drawable::attribute, drawable::attribute2, and drawable::id.
getPosition()
std::tuple< float, float > Drawable::getPosition () const
Definition at line 36 of file Drawable.cpp.
getRect()
std::tuple< int, int, int, int > Drawable::getRect () const
Definition at line 58 of file Drawable.cpp.
getSize()
std::tuple< float, float > Drawable::getSize () const
Definition at line 47 of file Drawable.cpp.
setAttribute()
void Drawable::setAttribute (std::string attribute) override virtual
Implements IComponentRType.
Definition at line 28 of file Drawable.cpp.
References IComponentRType::_attribute, and hasChanged.
setHasChanged()
void Drawable::setHasChanged (bool hasChanged)
Definition at line 92 of file Drawable.cpp.
References hasChanged.
setPosition()
void Drawable::setPosition (std::tuple< float, float > position)
Definition at line 41 of file Drawable.cpp.
References hasChanged.
Referenced by Drawable().
setRect()
void Drawable::setRect (std::tuple< int, int, int, int > rect)
Definition at line 63 of file Drawable.cpp.
References hasChanged.
Referenced by Drawable().
setSize()
void Drawable::setSize (std::tuple< float, float > size)
Definition at line 52 of file Drawable.cpp.
References hasChanged.
Referenced by Drawable().
storeStringInAttributes()
void Drawable::storeStringInAttributes (std::string str, DrawablePacket * drawablePacket)
Member Data Documentation
_drawablesCollision
std::vector<std::shared_ptr<Drawable> > Drawable::_drawablesCollision protected
Definition at line 52 of file Drawable.hpp.
_position
Position Drawable::_position protected
Definition at line 48 of file Drawable.hpp.
_rect
Rect Drawable::_rect protected
Definition at line 50 of file Drawable.hpp.
_size
Size Drawable::_size protected
Definition at line 49 of file Drawable.hpp.
_textureId
int Drawable::_textureId
Definition at line 46 of file Drawable.hpp.
Referenced by Drawable(), and getPacket().
hasChanged
bool Drawable::hasChanged = false protected
Definition at line 51 of file Drawable.hpp.
Referenced by getHasChanged(), setAttribute(), setHasChanged(), setPosition(), setRect(), and setSize().
The documentation for this class was generated from the following files:
src/lib/r_type/components/Drawable.hpp
src/lib/r_type/components/Drawable.cpp