RType: AComponent Class Reference
AComponent Class Reference
#include <AComponent.hpp>
Public Member Functions
AComponent (ClientCore *clientCore)
~AComponent () override=default
ComponentType getType () const override
void addActionTarget (std::shared_ptr< IComponent > component) override
void addSubComponent (std::shared_ptr< IComponent > component) override
void setAttribute (std::string attribute) override
std::string getAttribute () override
Public Member Functions inherited from IComponent
IComponent (ClientCore *clientCore)
virtual ~IComponent ()=default
virtual void action ()=0
virtual void display (sf::RenderWindow &window)=0
virtual void handleEvent (const sf::Event &event, sf::RenderWindow &window)=0
Additional Inherited Members
Protected Attributes inherited from IComponent
std::string _attribute
ComponentType _type
std::vector< std::shared_ptr< IComponent > > action_target
std::vector< std::shared_ptr< IComponent > > sub_components
ClientCore * _clientCore
Detailed Description
Definition at line 12 of file AComponent.hpp.
Constructor & Destructor Documentation
AComponent()
AComponent::AComponent (ClientCore * clientCore) inline explicit
Definition at line 14 of file AComponent.hpp.
References IComponent::IComponent().
Referenced by ButtonComponent::ButtonComponent(), InputComponent::InputComponent(), MusicComponent::MusicComponent(), SoundComponent::SoundComponent(), SpriteComponent::SpriteComponent(), and TextComponent::TextComponent().
~AComponent()
AComponent::~AComponent () override default
Member Function Documentation
addActionTarget()
void AComponent::addActionTarget (std::shared_ptr< IComponent > component) override virtual
Implements IComponent.
Definition at line 13 of file AComponent.cpp.
addSubComponent()
void AComponent::addSubComponent (std::shared_ptr< IComponent > component) override virtual
Implements IComponent.
Definition at line 18 of file AComponent.cpp.
getAttribute()
std::string AComponent::getAttribute () override virtual
Implements IComponent.
Definition at line 28 of file AComponent.cpp.
getType()
ComponentType AComponent::getType () const override virtual
Implements IComponent.
Definition at line 8 of file AComponent.cpp.
References IComponent::_type.
setAttribute()
void AComponent::setAttribute (std::string attribute) override virtual
Implements IComponent.
Definition at line 23 of file AComponent.cpp.
The documentation for this class was generated from the following files:
src/client/Components/AComponent.hpp
src/client/Components/AComponent.cpp