# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/simon/TEK3/Rtype

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/simon/TEK3/Rtype

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cpack --config ./CPackSourceConfig.cmake /home/simon/TEK3/Rtype/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"bin\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/simon/.local/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/TEK3/Rtype/CMakeFiles /home/simon/TEK3/Rtype//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/TEK3/Rtype/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named r-type_client

# Build rule for target.
r-type_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_client
.PHONY : r-type_client

# fast build rule for target.
r-type_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/build
.PHONY : r-type_client/fast

#=============================================================================
# Target rules for targets named lib_r_type

# Build rule for target.
lib_r_type: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_r_type
.PHONY : lib_r_type

# fast build rule for target.
lib_r_type/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/build
.PHONY : lib_r_type/fast

#=============================================================================
# Target rules for targets named r-type_server

# Build rule for target.
r-type_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_server
.PHONY : r-type_server

# fast build rule for target.
r-type_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/build
.PHONY : r-type_server/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build.make _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named sfml-window

# Build rule for target.
sfml-window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-window
.PHONY : sfml-window

# fast build rule for target.
sfml-window/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build.make _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build
.PHONY : sfml-window/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build.make _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-graphics

# Build rule for target.
sfml-graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-graphics
.PHONY : sfml-graphics

# fast build rule for target.
sfml-graphics/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build.make _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build
.PHONY : sfml-graphics/fast

#=============================================================================
# Target rules for targets named sfml-audio

# Build rule for target.
sfml-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-audio
.PHONY : sfml-audio

# fast build rule for target.
sfml-audio/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build.make _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build
.PHONY : sfml-audio/fast

networking/client/ClientSocket.o: networking/client/ClientSocket.cpp.o
.PHONY : networking/client/ClientSocket.o

# target to build an object file
networking/client/ClientSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/networking/client/ClientSocket.cpp.o
.PHONY : networking/client/ClientSocket.cpp.o

networking/client/ClientSocket.i: networking/client/ClientSocket.cpp.i
.PHONY : networking/client/ClientSocket.i

# target to preprocess a source file
networking/client/ClientSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/networking/client/ClientSocket.cpp.i
.PHONY : networking/client/ClientSocket.cpp.i

networking/client/ClientSocket.s: networking/client/ClientSocket.cpp.s
.PHONY : networking/client/ClientSocket.s

# target to generate assembly for a file
networking/client/ClientSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/networking/client/ClientSocket.cpp.s
.PHONY : networking/client/ClientSocket.cpp.s

networking/server/ServerSocket.o: networking/server/ServerSocket.cpp.o
.PHONY : networking/server/ServerSocket.o

# target to build an object file
networking/server/ServerSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/networking/server/ServerSocket.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/networking/server/ServerSocket.cpp.o
.PHONY : networking/server/ServerSocket.cpp.o

networking/server/ServerSocket.i: networking/server/ServerSocket.cpp.i
.PHONY : networking/server/ServerSocket.i

# target to preprocess a source file
networking/server/ServerSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/networking/server/ServerSocket.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/networking/server/ServerSocket.cpp.i
.PHONY : networking/server/ServerSocket.cpp.i

networking/server/ServerSocket.s: networking/server/ServerSocket.cpp.s
.PHONY : networking/server/ServerSocket.s

# target to generate assembly for a file
networking/server/ServerSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/networking/server/ServerSocket.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/networking/server/ServerSocket.cpp.s
.PHONY : networking/server/ServerSocket.cpp.s

src/client/ClientCore.o: src/client/ClientCore.cpp.o
.PHONY : src/client/ClientCore.o

# target to build an object file
src/client/ClientCore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/ClientCore.cpp.o
.PHONY : src/client/ClientCore.cpp.o

src/client/ClientCore.i: src/client/ClientCore.cpp.i
.PHONY : src/client/ClientCore.i

# target to preprocess a source file
src/client/ClientCore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/ClientCore.cpp.i
.PHONY : src/client/ClientCore.cpp.i

src/client/ClientCore.s: src/client/ClientCore.cpp.s
.PHONY : src/client/ClientCore.s

# target to generate assembly for a file
src/client/ClientCore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/ClientCore.cpp.s
.PHONY : src/client/ClientCore.cpp.s

src/client/Components/AComponent.o: src/client/Components/AComponent.cpp.o
.PHONY : src/client/Components/AComponent.o

# target to build an object file
src/client/Components/AComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/AComponent.cpp.o
.PHONY : src/client/Components/AComponent.cpp.o

src/client/Components/AComponent.i: src/client/Components/AComponent.cpp.i
.PHONY : src/client/Components/AComponent.i

# target to preprocess a source file
src/client/Components/AComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/AComponent.cpp.i
.PHONY : src/client/Components/AComponent.cpp.i

src/client/Components/AComponent.s: src/client/Components/AComponent.cpp.s
.PHONY : src/client/Components/AComponent.s

# target to generate assembly for a file
src/client/Components/AComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/AComponent.cpp.s
.PHONY : src/client/Components/AComponent.cpp.s

src/client/Components/Button/ButtonComponent.o: src/client/Components/Button/ButtonComponent.cpp.o
.PHONY : src/client/Components/Button/ButtonComponent.o

# target to build an object file
src/client/Components/Button/ButtonComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Button/ButtonComponent.cpp.o
.PHONY : src/client/Components/Button/ButtonComponent.cpp.o

src/client/Components/Button/ButtonComponent.i: src/client/Components/Button/ButtonComponent.cpp.i
.PHONY : src/client/Components/Button/ButtonComponent.i

# target to preprocess a source file
src/client/Components/Button/ButtonComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Button/ButtonComponent.cpp.i
.PHONY : src/client/Components/Button/ButtonComponent.cpp.i

src/client/Components/Button/ButtonComponent.s: src/client/Components/Button/ButtonComponent.cpp.s
.PHONY : src/client/Components/Button/ButtonComponent.s

# target to generate assembly for a file
src/client/Components/Button/ButtonComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Button/ButtonComponent.cpp.s
.PHONY : src/client/Components/Button/ButtonComponent.cpp.s

src/client/Components/Input/InputComponent.o: src/client/Components/Input/InputComponent.cpp.o
.PHONY : src/client/Components/Input/InputComponent.o

# target to build an object file
src/client/Components/Input/InputComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Input/InputComponent.cpp.o
.PHONY : src/client/Components/Input/InputComponent.cpp.o

src/client/Components/Input/InputComponent.i: src/client/Components/Input/InputComponent.cpp.i
.PHONY : src/client/Components/Input/InputComponent.i

# target to preprocess a source file
src/client/Components/Input/InputComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Input/InputComponent.cpp.i
.PHONY : src/client/Components/Input/InputComponent.cpp.i

src/client/Components/Input/InputComponent.s: src/client/Components/Input/InputComponent.cpp.s
.PHONY : src/client/Components/Input/InputComponent.s

# target to generate assembly for a file
src/client/Components/Input/InputComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Input/InputComponent.cpp.s
.PHONY : src/client/Components/Input/InputComponent.cpp.s

src/client/Components/Music/MusicComponent.o: src/client/Components/Music/MusicComponent.cpp.o
.PHONY : src/client/Components/Music/MusicComponent.o

# target to build an object file
src/client/Components/Music/MusicComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Music/MusicComponent.cpp.o
.PHONY : src/client/Components/Music/MusicComponent.cpp.o

src/client/Components/Music/MusicComponent.i: src/client/Components/Music/MusicComponent.cpp.i
.PHONY : src/client/Components/Music/MusicComponent.i

# target to preprocess a source file
src/client/Components/Music/MusicComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Music/MusicComponent.cpp.i
.PHONY : src/client/Components/Music/MusicComponent.cpp.i

src/client/Components/Music/MusicComponent.s: src/client/Components/Music/MusicComponent.cpp.s
.PHONY : src/client/Components/Music/MusicComponent.s

# target to generate assembly for a file
src/client/Components/Music/MusicComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Music/MusicComponent.cpp.s
.PHONY : src/client/Components/Music/MusicComponent.cpp.s

src/client/Components/Sound/SoundComponent.o: src/client/Components/Sound/SoundComponent.cpp.o
.PHONY : src/client/Components/Sound/SoundComponent.o

# target to build an object file
src/client/Components/Sound/SoundComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Sound/SoundComponent.cpp.o
.PHONY : src/client/Components/Sound/SoundComponent.cpp.o

src/client/Components/Sound/SoundComponent.i: src/client/Components/Sound/SoundComponent.cpp.i
.PHONY : src/client/Components/Sound/SoundComponent.i

# target to preprocess a source file
src/client/Components/Sound/SoundComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Sound/SoundComponent.cpp.i
.PHONY : src/client/Components/Sound/SoundComponent.cpp.i

src/client/Components/Sound/SoundComponent.s: src/client/Components/Sound/SoundComponent.cpp.s
.PHONY : src/client/Components/Sound/SoundComponent.s

# target to generate assembly for a file
src/client/Components/Sound/SoundComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Sound/SoundComponent.cpp.s
.PHONY : src/client/Components/Sound/SoundComponent.cpp.s

src/client/Components/Sprite/SpriteComponent.o: src/client/Components/Sprite/SpriteComponent.cpp.o
.PHONY : src/client/Components/Sprite/SpriteComponent.o

# target to build an object file
src/client/Components/Sprite/SpriteComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Sprite/SpriteComponent.cpp.o
.PHONY : src/client/Components/Sprite/SpriteComponent.cpp.o

src/client/Components/Sprite/SpriteComponent.i: src/client/Components/Sprite/SpriteComponent.cpp.i
.PHONY : src/client/Components/Sprite/SpriteComponent.i

# target to preprocess a source file
src/client/Components/Sprite/SpriteComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Sprite/SpriteComponent.cpp.i
.PHONY : src/client/Components/Sprite/SpriteComponent.cpp.i

src/client/Components/Sprite/SpriteComponent.s: src/client/Components/Sprite/SpriteComponent.cpp.s
.PHONY : src/client/Components/Sprite/SpriteComponent.s

# target to generate assembly for a file
src/client/Components/Sprite/SpriteComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Sprite/SpriteComponent.cpp.s
.PHONY : src/client/Components/Sprite/SpriteComponent.cpp.s

src/client/Components/Text/TextComponent.o: src/client/Components/Text/TextComponent.cpp.o
.PHONY : src/client/Components/Text/TextComponent.o

# target to build an object file
src/client/Components/Text/TextComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Text/TextComponent.cpp.o
.PHONY : src/client/Components/Text/TextComponent.cpp.o

src/client/Components/Text/TextComponent.i: src/client/Components/Text/TextComponent.cpp.i
.PHONY : src/client/Components/Text/TextComponent.i

# target to preprocess a source file
src/client/Components/Text/TextComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Text/TextComponent.cpp.i
.PHONY : src/client/Components/Text/TextComponent.cpp.i

src/client/Components/Text/TextComponent.s: src/client/Components/Text/TextComponent.cpp.s
.PHONY : src/client/Components/Text/TextComponent.s

# target to generate assembly for a file
src/client/Components/Text/TextComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Components/Text/TextComponent.cpp.s
.PHONY : src/client/Components/Text/TextComponent.cpp.s

src/client/Scenes/AScene.o: src/client/Scenes/AScene.cpp.o
.PHONY : src/client/Scenes/AScene.o

# target to build an object file
src/client/Scenes/AScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/AScene.cpp.o
.PHONY : src/client/Scenes/AScene.cpp.o

src/client/Scenes/AScene.i: src/client/Scenes/AScene.cpp.i
.PHONY : src/client/Scenes/AScene.i

# target to preprocess a source file
src/client/Scenes/AScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/AScene.cpp.i
.PHONY : src/client/Scenes/AScene.cpp.i

src/client/Scenes/AScene.s: src/client/Scenes/AScene.cpp.s
.PHONY : src/client/Scenes/AScene.s

# target to generate assembly for a file
src/client/Scenes/AScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/AScene.cpp.s
.PHONY : src/client/Scenes/AScene.cpp.s

src/client/Scenes/Game/GameScene.o: src/client/Scenes/Game/GameScene.cpp.o
.PHONY : src/client/Scenes/Game/GameScene.o

# target to build an object file
src/client/Scenes/Game/GameScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/Game/GameScene.cpp.o
.PHONY : src/client/Scenes/Game/GameScene.cpp.o

src/client/Scenes/Game/GameScene.i: src/client/Scenes/Game/GameScene.cpp.i
.PHONY : src/client/Scenes/Game/GameScene.i

# target to preprocess a source file
src/client/Scenes/Game/GameScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/Game/GameScene.cpp.i
.PHONY : src/client/Scenes/Game/GameScene.cpp.i

src/client/Scenes/Game/GameScene.s: src/client/Scenes/Game/GameScene.cpp.s
.PHONY : src/client/Scenes/Game/GameScene.s

# target to generate assembly for a file
src/client/Scenes/Game/GameScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/Game/GameScene.cpp.s
.PHONY : src/client/Scenes/Game/GameScene.cpp.s

src/client/Scenes/Menu/MainScene.o: src/client/Scenes/Menu/MainScene.cpp.o
.PHONY : src/client/Scenes/Menu/MainScene.o

# target to build an object file
src/client/Scenes/Menu/MainScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/Menu/MainScene.cpp.o
.PHONY : src/client/Scenes/Menu/MainScene.cpp.o

src/client/Scenes/Menu/MainScene.i: src/client/Scenes/Menu/MainScene.cpp.i
.PHONY : src/client/Scenes/Menu/MainScene.i

# target to preprocess a source file
src/client/Scenes/Menu/MainScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/Menu/MainScene.cpp.i
.PHONY : src/client/Scenes/Menu/MainScene.cpp.i

src/client/Scenes/Menu/MainScene.s: src/client/Scenes/Menu/MainScene.cpp.s
.PHONY : src/client/Scenes/Menu/MainScene.s

# target to generate assembly for a file
src/client/Scenes/Menu/MainScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/Menu/MainScene.cpp.s
.PHONY : src/client/Scenes/Menu/MainScene.cpp.s

src/client/Scenes/Menu/MenuScene.o: src/client/Scenes/Menu/MenuScene.cpp.o
.PHONY : src/client/Scenes/Menu/MenuScene.o

# target to build an object file
src/client/Scenes/Menu/MenuScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/Menu/MenuScene.cpp.o
.PHONY : src/client/Scenes/Menu/MenuScene.cpp.o

src/client/Scenes/Menu/MenuScene.i: src/client/Scenes/Menu/MenuScene.cpp.i
.PHONY : src/client/Scenes/Menu/MenuScene.i

# target to preprocess a source file
src/client/Scenes/Menu/MenuScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/Menu/MenuScene.cpp.i
.PHONY : src/client/Scenes/Menu/MenuScene.cpp.i

src/client/Scenes/Menu/MenuScene.s: src/client/Scenes/Menu/MenuScene.cpp.s
.PHONY : src/client/Scenes/Menu/MenuScene.s

# target to generate assembly for a file
src/client/Scenes/Menu/MenuScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Scenes/Menu/MenuScene.cpp.s
.PHONY : src/client/Scenes/Menu/MenuScene.cpp.s

src/client/main.o: src/client/main.cpp.o
.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i
.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s
.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/lib/r_type/RType.o: src/lib/r_type/RType.cpp.o
.PHONY : src/lib/r_type/RType.o

# target to build an object file
src/lib/r_type/RType.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/RType.cpp.o
.PHONY : src/lib/r_type/RType.cpp.o

src/lib/r_type/RType.i: src/lib/r_type/RType.cpp.i
.PHONY : src/lib/r_type/RType.i

# target to preprocess a source file
src/lib/r_type/RType.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/RType.cpp.i
.PHONY : src/lib/r_type/RType.cpp.i

src/lib/r_type/RType.s: src/lib/r_type/RType.cpp.s
.PHONY : src/lib/r_type/RType.s

# target to generate assembly for a file
src/lib/r_type/RType.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/RType.cpp.s
.PHONY : src/lib/r_type/RType.cpp.s

src/lib/r_type/Scenes/AScene.o: src/lib/r_type/Scenes/AScene.cpp.o
.PHONY : src/lib/r_type/Scenes/AScene.o

# target to build an object file
src/lib/r_type/Scenes/AScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/Scenes/AScene.cpp.o
.PHONY : src/lib/r_type/Scenes/AScene.cpp.o

src/lib/r_type/Scenes/AScene.i: src/lib/r_type/Scenes/AScene.cpp.i
.PHONY : src/lib/r_type/Scenes/AScene.i

# target to preprocess a source file
src/lib/r_type/Scenes/AScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/Scenes/AScene.cpp.i
.PHONY : src/lib/r_type/Scenes/AScene.cpp.i

src/lib/r_type/Scenes/AScene.s: src/lib/r_type/Scenes/AScene.cpp.s
.PHONY : src/lib/r_type/Scenes/AScene.s

# target to generate assembly for a file
src/lib/r_type/Scenes/AScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/Scenes/AScene.cpp.s
.PHONY : src/lib/r_type/Scenes/AScene.cpp.s

src/lib/r_type/Scenes/Game/Game.o: src/lib/r_type/Scenes/Game/Game.cpp.o
.PHONY : src/lib/r_type/Scenes/Game/Game.o

# target to build an object file
src/lib/r_type/Scenes/Game/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/Scenes/Game/Game.cpp.o
.PHONY : src/lib/r_type/Scenes/Game/Game.cpp.o

src/lib/r_type/Scenes/Game/Game.i: src/lib/r_type/Scenes/Game/Game.cpp.i
.PHONY : src/lib/r_type/Scenes/Game/Game.i

# target to preprocess a source file
src/lib/r_type/Scenes/Game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/Scenes/Game/Game.cpp.i
.PHONY : src/lib/r_type/Scenes/Game/Game.cpp.i

src/lib/r_type/Scenes/Game/Game.s: src/lib/r_type/Scenes/Game/Game.cpp.s
.PHONY : src/lib/r_type/Scenes/Game/Game.s

# target to generate assembly for a file
src/lib/r_type/Scenes/Game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/Scenes/Game/Game.cpp.s
.PHONY : src/lib/r_type/Scenes/Game/Game.cpp.s

src/lib/r_type/components/Drawable.o: src/lib/r_type/components/Drawable.cpp.o
.PHONY : src/lib/r_type/components/Drawable.o

# target to build an object file
src/lib/r_type/components/Drawable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/components/Drawable.cpp.o
.PHONY : src/lib/r_type/components/Drawable.cpp.o

src/lib/r_type/components/Drawable.i: src/lib/r_type/components/Drawable.cpp.i
.PHONY : src/lib/r_type/components/Drawable.i

# target to preprocess a source file
src/lib/r_type/components/Drawable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/components/Drawable.cpp.i
.PHONY : src/lib/r_type/components/Drawable.cpp.i

src/lib/r_type/components/Drawable.s: src/lib/r_type/components/Drawable.cpp.s
.PHONY : src/lib/r_type/components/Drawable.s

# target to generate assembly for a file
src/lib/r_type/components/Drawable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/components/Drawable.cpp.s
.PHONY : src/lib/r_type/components/Drawable.cpp.s

src/lib/r_type/services/AService.o: src/lib/r_type/services/AService.cpp.o
.PHONY : src/lib/r_type/services/AService.o

# target to build an object file
src/lib/r_type/services/AService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/services/AService.cpp.o
.PHONY : src/lib/r_type/services/AService.cpp.o

src/lib/r_type/services/AService.i: src/lib/r_type/services/AService.cpp.i
.PHONY : src/lib/r_type/services/AService.i

# target to preprocess a source file
src/lib/r_type/services/AService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/services/AService.cpp.i
.PHONY : src/lib/r_type/services/AService.cpp.i

src/lib/r_type/services/AService.s: src/lib/r_type/services/AService.cpp.s
.PHONY : src/lib/r_type/services/AService.s

# target to generate assembly for a file
src/lib/r_type/services/AService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/services/AService.cpp.s
.PHONY : src/lib/r_type/services/AService.cpp.s

src/lib/r_type/services/Graphic.o: src/lib/r_type/services/Graphic.cpp.o
.PHONY : src/lib/r_type/services/Graphic.o

# target to build an object file
src/lib/r_type/services/Graphic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/services/Graphic.cpp.o
.PHONY : src/lib/r_type/services/Graphic.cpp.o

src/lib/r_type/services/Graphic.i: src/lib/r_type/services/Graphic.cpp.i
.PHONY : src/lib/r_type/services/Graphic.i

# target to preprocess a source file
src/lib/r_type/services/Graphic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/services/Graphic.cpp.i
.PHONY : src/lib/r_type/services/Graphic.cpp.i

src/lib/r_type/services/Graphic.s: src/lib/r_type/services/Graphic.cpp.s
.PHONY : src/lib/r_type/services/Graphic.s

# target to generate assembly for a file
src/lib/r_type/services/Graphic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_r_type.dir/build.make CMakeFiles/lib_r_type.dir/src/lib/r_type/services/Graphic.cpp.s
.PHONY : src/lib/r_type/services/Graphic.cpp.s

src/server/Server.o: src/server/Server.cpp.o
.PHONY : src/server/Server.o

# target to build an object file
src/server/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/Server.cpp.o
.PHONY : src/server/Server.cpp.o

src/server/Server.i: src/server/Server.cpp.i
.PHONY : src/server/Server.i

# target to preprocess a source file
src/server/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/Server.cpp.i
.PHONY : src/server/Server.cpp.i

src/server/Server.s: src/server/Server.cpp.s
.PHONY : src/server/Server.s

# target to generate assembly for a file
src/server/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/Server.cpp.s
.PHONY : src/server/Server.cpp.s

src/server/main.o: src/server/main.cpp.o
.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i
.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s
.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... lib_r_type"
	@echo "... r-type_client"
	@echo "... r-type_server"
	@echo "... sfml-audio"
	@echo "... sfml-graphics"
	@echo "... sfml-network"
	@echo "... sfml-system"
	@echo "... sfml-window"
	@echo "... networking/client/ClientSocket.o"
	@echo "... networking/client/ClientSocket.i"
	@echo "... networking/client/ClientSocket.s"
	@echo "... networking/server/ServerSocket.o"
	@echo "... networking/server/ServerSocket.i"
	@echo "... networking/server/ServerSocket.s"
	@echo "... src/client/ClientCore.o"
	@echo "... src/client/ClientCore.i"
	@echo "... src/client/ClientCore.s"
	@echo "... src/client/Components/AComponent.o"
	@echo "... src/client/Components/AComponent.i"
	@echo "... src/client/Components/AComponent.s"
	@echo "... src/client/Components/Button/ButtonComponent.o"
	@echo "... src/client/Components/Button/ButtonComponent.i"
	@echo "... src/client/Components/Button/ButtonComponent.s"
	@echo "... src/client/Components/Input/InputComponent.o"
	@echo "... src/client/Components/Input/InputComponent.i"
	@echo "... src/client/Components/Input/InputComponent.s"
	@echo "... src/client/Components/Music/MusicComponent.o"
	@echo "... src/client/Components/Music/MusicComponent.i"
	@echo "... src/client/Components/Music/MusicComponent.s"
	@echo "... src/client/Components/Sound/SoundComponent.o"
	@echo "... src/client/Components/Sound/SoundComponent.i"
	@echo "... src/client/Components/Sound/SoundComponent.s"
	@echo "... src/client/Components/Sprite/SpriteComponent.o"
	@echo "... src/client/Components/Sprite/SpriteComponent.i"
	@echo "... src/client/Components/Sprite/SpriteComponent.s"
	@echo "... src/client/Components/Text/TextComponent.o"
	@echo "... src/client/Components/Text/TextComponent.i"
	@echo "... src/client/Components/Text/TextComponent.s"
	@echo "... src/client/Scenes/AScene.o"
	@echo "... src/client/Scenes/AScene.i"
	@echo "... src/client/Scenes/AScene.s"
	@echo "... src/client/Scenes/Game/GameScene.o"
	@echo "... src/client/Scenes/Game/GameScene.i"
	@echo "... src/client/Scenes/Game/GameScene.s"
	@echo "... src/client/Scenes/Menu/MainScene.o"
	@echo "... src/client/Scenes/Menu/MainScene.i"
	@echo "... src/client/Scenes/Menu/MainScene.s"
	@echo "... src/client/Scenes/Menu/MenuScene.o"
	@echo "... src/client/Scenes/Menu/MenuScene.i"
	@echo "... src/client/Scenes/Menu/MenuScene.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/lib/r_type/RType.o"
	@echo "... src/lib/r_type/RType.i"
	@echo "... src/lib/r_type/RType.s"
	@echo "... src/lib/r_type/Scenes/AScene.o"
	@echo "... src/lib/r_type/Scenes/AScene.i"
	@echo "... src/lib/r_type/Scenes/AScene.s"
	@echo "... src/lib/r_type/Scenes/Game/Game.o"
	@echo "... src/lib/r_type/Scenes/Game/Game.i"
	@echo "... src/lib/r_type/Scenes/Game/Game.s"
	@echo "... src/lib/r_type/components/Drawable.o"
	@echo "... src/lib/r_type/components/Drawable.i"
	@echo "... src/lib/r_type/components/Drawable.s"
	@echo "... src/lib/r_type/services/AService.o"
	@echo "... src/lib/r_type/services/AService.i"
	@echo "... src/lib/r_type/services/AService.s"
	@echo "... src/lib/r_type/services/Graphic.o"
	@echo "... src/lib/r_type/services/Graphic.i"
	@echo "... src/lib/r_type/services/Graphic.s"
	@echo "... src/server/Server.o"
	@echo "... src/server/Server.i"
	@echo "... src/server/Server.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

